# Generated by Django 2.2.2 on 2020-09-30 06:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='pics_country')),
                ('heading', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(default=True, max_length=40)),
                ('content', models.TextField()),
                ('date_time', models.DateTimeField(default=datetime.datetime(2020, 9, 30, 12, 4, 3, 715300))),
                ('category', models.CharField(choices=[('World', 'World'), ('Country', 'Country'), ('Sports', 'Sports'), ('Business', 'Business'), ('Carrier', 'Carrier'), ('Entertainment', 'Entertainment'), ('Tech', 'Tech'), ('Startup', 'Startup'), ('Politics', 'Politics')], max_length=20)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
