# Generated by Django 3.0.8 on 2020-07-05 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 23, 28, 2, 560764)),
        ),
    ]
