# Generated by Django 3.0.8 on 2020-07-05 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_auto_20200705_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foreign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics_country')),
                ('heading', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('date_time', models.DateTimeField(default=datetime.datetime(2020, 7, 6, 0, 56, 35, 424986))),
            ],
        ),
        migrations.DeleteModel(
            name='foregn',
        ),
        migrations.DeleteModel(
            name='top_news',
        ),
        migrations.AddField(
            model_name='business',
            name='content',
            field=models.TextField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 6, 0, 56, 35, 424986)),
        ),
        migrations.AddField(
            model_name='business',
            name='heading',
            field=models.CharField(default=100, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(default=100, upload_to='pics_country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='title',
            field=models.CharField(default=20, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entertainment',
            name='content',
            field=models.TextField(default=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entertainment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 6, 0, 56, 35, 424986)),
        ),
        migrations.AddField(
            model_name='entertainment',
            name='heading',
            field=models.CharField(default=100, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entertainment',
            name='image',
            field=models.ImageField(default=100, upload_to='pics_country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entertainment',
            name='title',
            field=models.CharField(default=100, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='politics',
            name='content',
            field=models.TextField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='politics',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 6, 0, 56, 35, 433024)),
        ),
        migrations.AddField(
            model_name='politics',
            name='heading',
            field=models.CharField(default=100, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='politics',
            name='image',
            field=models.ImageField(default=100, upload_to='pics_country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='politics',
            name='title',
            field=models.CharField(default=100, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startup',
            name='content',
            field=models.TextField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startup',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 6, 0, 56, 35, 424986)),
        ),
        migrations.AddField(
            model_name='startup',
            name='heading',
            field=models.CharField(default=100, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startup',
            name='image',
            field=models.ImageField(default=100, upload_to='pics_country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startup',
            name='title',
            field=models.CharField(default=100, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tech',
            name='content',
            field=models.TextField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tech',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 6, 0, 56, 35, 424986)),
        ),
        migrations.AddField(
            model_name='tech',
            name='heading',
            field=models.CharField(default=100, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tech',
            name='image',
            field=models.ImageField(default=100, upload_to='pics_country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tech',
            name='title',
            field=models.CharField(default=100, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 6, 0, 56, 35, 424986)),
        ),
    ]
