# Generated by Django 3.0.8 on 2020-07-05 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_auto_20200706_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 6, 2, 50, 1, 179967)),
        ),
        migrations.AlterField(
            model_name='country',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 6, 2, 50, 1, 176977)),
        ),
        migrations.AlterField(
            model_name='entertainment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 6, 2, 50, 1, 178970)),
        ),
        migrations.AlterField(
            model_name='foreign',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 6, 2, 50, 1, 177976)),
        ),
        migrations.AlterField(
            model_name='politics',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 6, 2, 50, 1, 180969)),
        ),
        migrations.AlterField(
            model_name='startup',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 6, 2, 50, 1, 180969)),
        ),
        migrations.AlterField(
            model_name='tech',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 6, 2, 50, 1, 178970)),
        ),
    ]
