# Generated by Django 2.2.2 on 2020-07-16 02:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0007_auto_20200715_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics_foregn')),
                ('heading', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('date_time', models.DateTimeField(default=datetime.datetime(2020, 7, 16, 8, 5, 40, 998059))),
            ],
        ),
        migrations.DeleteModel(
            name='Foreign',
        ),
        migrations.AddField(
            model_name='country',
            name='category',
            field=models.CharField(choices=[('World', 'World'), ('Country', 'Country'), ('Sports', 'Sports'), ('Business', 'Business'), ('Carrier', 'Carrier'), ('Entertainment', 'Entertainment'), ('Tech', 'Tech'), ('Startup', 'Startup'), ('Politics', 'Politics')], default=25, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='business',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 8, 5, 41, 1050)),
        ),
        migrations.AlterField(
            model_name='country',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 8, 5, 40, 997062)),
        ),
        migrations.AlterField(
            model_name='entertainment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 8, 5, 41, 53)),
        ),
        migrations.AlterField(
            model_name='politics',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 8, 5, 41, 2048)),
        ),
        migrations.AlterField(
            model_name='sports',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 8, 5, 41, 3045)),
        ),
        migrations.AlterField(
            model_name='startup',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 8, 5, 41, 2048)),
        ),
        migrations.AlterField(
            model_name='tech',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 8, 5, 41, 53)),
        ),
        migrations.AlterField(
            model_name='trending',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 8, 5, 40, 999055)),
        ),
    ]
