# Generated by Django 2.2.2 on 2020-07-17 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0008_auto_20200716_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 11, 56, 26, 912284)),
        ),
        migrations.AlterField(
            model_name='country',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 11, 56, 26, 904434)),
        ),
        migrations.AlterField(
            model_name='entertainment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 11, 56, 26, 904434)),
        ),
        migrations.AlterField(
            model_name='politics',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 11, 56, 26, 912284)),
        ),
        migrations.AlterField(
            model_name='sports',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 11, 56, 26, 912284)),
        ),
        migrations.AlterField(
            model_name='startup',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 11, 56, 26, 912284)),
        ),
        migrations.AlterField(
            model_name='tech',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 11, 56, 26, 912284)),
        ),
        migrations.AlterField(
            model_name='trending',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 11, 56, 26, 904434)),
        ),
        migrations.AlterField(
            model_name='world',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 11, 56, 26, 904434)),
        ),
    ]
