# Generated by Django 2.2.2 on 2020-07-19 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0009_auto_20200717_1156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='business',
        ),
        migrations.DeleteModel(
            name='entertainment',
        ),
        migrations.DeleteModel(
            name='politics',
        ),
        migrations.DeleteModel(
            name='Sports',
        ),
        migrations.DeleteModel(
            name='startup',
        ),
        migrations.DeleteModel(
            name='tech',
        ),
        migrations.DeleteModel(
            name='TopNews',
        ),
        migrations.DeleteModel(
            name='Trending',
        ),
        migrations.DeleteModel(
            name='World',
        ),
        migrations.AlterField(
            model_name='country',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 9, 2, 40, 749)),
        ),
    ]
