# Generated by Django 2.2.2 on 2020-07-19 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0010_auto_20200719_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 9, 23, 4, 687815)),
        ),
    ]
