# Generated by Django 2.2.2 on 2020-07-19 05:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news_app', '0011_auto_20200719_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='author',
            field=models.ForeignKey(default=55, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 10, 58, 50, 49867)),
        ),
    ]
