# Generated by Django 2.2.2 on 2020-07-19 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0017_auto_20200719_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 11, 8, 34, 558185)),
        ),
    ]
