# Generated by Django 2.2.2 on 2020-07-19 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0018_auto_20200719_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='author',
        ),
        migrations.AlterField(
            model_name='country',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 11, 9, 22, 164665)),
        ),
    ]
