# Generated by Django 2.2.2 on 2020-07-20 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0024_auto_20200719_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='date_time',
            field=models.DateTimeField(default=datetime.date(2020, 7, 20)),
        ),
    ]
