# Generated by Django 2.2.2 on 2020-07-20 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0025_auto_20200720_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 20, 11, 47, 50, 369240)),
        ),
    ]
